# Configuração do Netlify para Clínica FISIO
[build]
  # Diretório de publicação
  publish = "."
  
  # Comando de build (se necessário)
  # command = "npm run build"

# Configuração do Netlify CMS
[build.environment]
  # Variáveis de ambiente se necessárias
  NODE_VERSION = "18"

# Redirecionamentos
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Headers para segurança
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para arquivos de posts
[[headers]]
  for = "/posts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=3600"

# Headers para imagens do blog
[[headers]]
  for = "/imagens/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuração do Git Gateway (para Netlify CMS)
[context.production]
  # Identity settings são configuradas no painel do Netlify

# Configurações de formulários (se necessário no futuro)
[context.production.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"